# @format

_base_:
  - ../../base/mipnerf360.yaml
  - ../../base/triangle-splatting.yaml

experiment:
  name: triangle_splatting_treehill

dataset:
  scene: treehill
  image_dir: images_4
  resolution: 1

trainer:
  outdoor: true
