# @format

adapter:
  render_params:
    gamma_rescale: true
    ste_threshold: 0.3
    sort_level: 2
    bg_color: white

dataset:
  resolution: 2

eval:
  mesh:
    geometry_mode: pcd

d2ts:
  strategy: opaque
