# @format

_base_: triangle-splatting-caps.yaml

trainer:
  type: triangle-splatting
  max_steps: 30000
  white_background: false
  densify_until_iter: 25000

adapter:
  type: triangle-splatting
  checkpoint: outputs/{method}/{dataset}/{scene}/point_cloud/iteration_{max_steps}
