# @format

_base_:
  - ../../base/nerf_synthetic.yaml
  - ../../base/mesh-splatting.yaml

experiment:
  name: mesh_splatting_nerf_synthetic_ship

dataset:
  scene: ship

trainer:
  white_background: true

adapter:
  render_params:
    bg_color: white
