# @format

_base_:
  - ../../base/nerf_synthetic.yaml
  - ../../base/triangle-splatting.yaml

experiment:
  name: triangle_splatting_nerf_synthetic_drums

dataset:
  scene: drums

trainer:
  white_background: true

adapter:
  render_params:
    bg_color: white
