# @format

_base_:
  - ../../base/nerf_synthetic.yaml
  - ../../base/diffsoup.yaml

experiment:
  name: diffsoup_nerf_synthetic_lego

dataset:
  scene: lego

trainer:
  mobilenerf_root: data/mobilenerf_results
  downscale: 1

adapter:
  render_params:
    bg_color: white
